package com.example.demo.entities;
// Generated 12:33:13 14 thg 12, 2024 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

/**
 * Actor generated by hbm2java
 */
@Entity
@Table(name = "actor")
public class Actor implements java.io.Serializable {

	private Integer id;
	private String name;
	private String imageUrl;
	private Set<Movies> movieses = new HashSet<Movies>(0);

	public Actor() {
	}

	public Actor(String name) {
		this.name = name;
	}

	public Actor(String name, String imageUrl, Set<Movies> movieses) {
		this.name = name;
		this.imageUrl = imageUrl;
		this.movieses = movieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "actors")
	public Set<Movies> getMovieses() {
		return this.movieses;
	}

	public void setMovieses(Set<Movies> movieses) {
		this.movieses = movieses;
	}

}
