package com.example.demo.entities;
// Generated 21:44:05 10 thg 2, 2025 by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Bookings generated by hbm2java
 */
@Entity
@Table(name = "bookings")
public class Bookings implements java.io.Serializable {

	private Integer bookingId;
	private Users users;
	private Date bookingDate;
	private BigDecimal totalPrice;
	private String barcode;
	private String status;
	private Set<BookingDetails> bookingDetailses = new HashSet<BookingDetails>(0);

	public Bookings() {
	}

	public Bookings(Users users, Date bookingDate, BigDecimal totalPrice, String barcode, String status) {
		this.users = users;
		this.bookingDate = bookingDate;
		this.totalPrice = totalPrice;
		this.barcode = barcode;
		this.status = status;
	}

	public Bookings(Users users, Date bookingDate, BigDecimal totalPrice, String barcode, String status,
			Set<BookingDetails> bookingDetailses) {
		this.users = users;
		this.bookingDate = bookingDate;
		this.totalPrice = totalPrice;
		this.barcode = barcode;
		this.status = status;
		this.bookingDetailses = bookingDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "booking_id", unique = true, nullable = false)
	public Integer getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(Integer bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "booking_date", nullable = false, length = 19)
	public Date getBookingDate() {
		return this.bookingDate;
	}

	public void setBookingDate(Date bookingDate) {
		this.bookingDate = bookingDate;
	}

	@Column(name = "total_price", nullable = false, precision = 10)
	public BigDecimal getTotalPrice() {
		return this.totalPrice;
	}

	public void setTotalPrice(BigDecimal totalPrice) {
		this.totalPrice = totalPrice;
	}

	@Column(name = "barcode", nullable = false)
	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}
	
	@Column(name = "status", nullable = false, length = 65535)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bookings")
	public Set<BookingDetails> getBookingDetailses() {
		return this.bookingDetailses;
	}

	public void setBookingDetailses(Set<BookingDetails> bookingDetailses) {
		this.bookingDetailses = bookingDetailses;
	}

}
