package com.example.demo.entities;
// Generated Dec 2, 2024, 8:44:12 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
/**
 * BookingDetails generated by hbm2java
 */
@Entity
@Table(name = "booking_details")
public class BookingDetails implements java.io.Serializable {

	private Integer bookingDetailId;
	private Bookings bookings;
	private Seats seats;
	private Showtimes showtimes;
	private BigDecimal price;

	public BookingDetails() {
	}

	public BookingDetails(Bookings bookings, Seats seats, Showtimes showtimes, BigDecimal price) {
		this.bookings = bookings;
		this.seats = seats;
		this.showtimes = showtimes;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "booking_detail_id", unique = true, nullable = false)
	public Integer getBookingDetailId() {
		return this.bookingDetailId;
	}

	public void setBookingDetailId(Integer bookingDetailId) {
		this.bookingDetailId = bookingDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "booking_id", nullable = false)
	public Bookings getBookings() {
		return this.bookings;
	}

	public void setBookings(Bookings bookings) {
		this.bookings = bookings;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seat_id", nullable = false)
	public Seats getSeats() {
		return this.seats;
	}

	public void setSeats(Seats seats) {
		this.seats = seats;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "showtime_id", nullable = false)
	public Showtimes getShowtimes() {
		return this.showtimes;
	}

	public void setShowtimes(Showtimes showtimes) {
		this.showtimes = showtimes;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

}
