package com.example.demo.entities;
// Generated Dec 2, 2024, 8:44:12 PM by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Brands generated by hbm2java
 */
@Entity
@Table(name = "brands")
public class Brands implements java.io.Serializable {

	private Integer brandId;
	private Users users;
	private String name;
	private String imageUrl;
	private Date createdAt;
	private Set<Theaters> theaterses = new HashSet<Theaters>(0);

	public Brands() {
	}

	public Brands(Users users, String name, Date createdAt) {
		this.users = users;
		this.name = name;
		this.createdAt = createdAt;
	}

	public Brands(Users users, String name, String imageUrl, Date createdAt, Set<Theaters> theaterses) {
		this.users = users;
		this.name = name;
		this.imageUrl = imageUrl;
		this.createdAt = createdAt;
		this.theaterses = theaterses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "brand_id", unique = true, nullable = false)
	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "owner_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "image_url")
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brands")
	public Set<Theaters> getTheaterses() {
		return this.theaterses;
	}

	public void setTheaterses(Set<Theaters> theaterses) {
		this.theaterses = theaterses;
	}

}
