package com.example.demo.entities;
// Generated Dec 2, 2024, 8:44:12 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.Table;

/**
 * Genres generated by hbm2java
 */
@Entity
@Table(name = "genres")
public class Genres implements java.io.Serializable {

	private Integer genreId;
	private String name;
	private Set<Movies> movieses = new HashSet<Movies>(0);

	public Genres() {
	}

	public Genres(String name) {
		this.name = name;
	}

	public Genres(String name, Set<Movies> movieses) {
		this.name = name;
		this.movieses = movieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "genre_id", unique = true, nullable = false)
	public Integer getGenreId() {
		return this.genreId;
	}

	public void setGenreId(Integer genreId) {
		this.genreId = genreId;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "genreses")
	public Set<Movies> getMovieses() {
		return this.movieses;
	}

	public void setMovieses(Set<Movies> movieses) {
		this.movieses = movieses;
	}

}
