package com.example.demo.entities;
// Generated Dec 2, 2024, 8:44:12 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Locations generated by hbm2java
 */
@Entity
@Table(name = "locations")
public class Locations implements java.io.Serializable {

	private Integer locationId;
	private String city;
	private Set<Theaters> theaterses = new HashSet<Theaters>(0);

	public Locations() {
	}

	public Locations(String city) {
		this.city = city;
	}

	public Locations(String city, Set<Theaters> theaterses) {
		this.city = city;
		this.theaterses = theaterses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "location_id", unique = true, nullable = false)
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	@Column(name = "city", nullable = false, length = 100)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "locations")
	public Set<Theaters> getTheaterses() {
		return this.theaterses;
	}

	public void setTheaterses(Set<Theaters> theaterses) {
		this.theaterses = theaterses;
	}

}
