package com.example.demo.entities;
// Generated 21:03:18 27 thg 12, 2024 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;

/**
 * MovieShowtimeScreen generated by hbm2java
 */
@Entity
@Table(name = "movie_showtime_screen", uniqueConstraints = @UniqueConstraint(columnNames = "showtime_id"))
public class MovieShowtimeScreen implements java.io.Serializable {

	private Integer id;
	private Movies movies;
	private Screens screens;
	private Showtimes showtimes;

	public MovieShowtimeScreen() {
	}

	public MovieShowtimeScreen(Movies movies, Screens screens, Showtimes showtimes) {
		this.movies = movies;
		this.screens = screens;
		this.showtimes = showtimes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false)
	public Movies getMovies() {
		return this.movies;
	}

	public void setMovies(Movies movies) {
		this.movies = movies;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screen_id", nullable = false)
	public Screens getScreens() {
		return this.screens;
	}

	public void setScreens(Screens screens) {
		this.screens = screens;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "showtime_id", unique = true, nullable = false)
	public Showtimes getShowtimes() {
		return this.showtimes;
	}

	public void setShowtimes(Showtimes showtimes) {
		this.showtimes = showtimes;
	}

}
