package com.example.demo.entities;
// Generated 21:03:18 27 thg 12, 2024 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Screens generated by hbm2java
 */
@Entity
@Table(name = "screens")
public class Screens implements java.io.Serializable {

	private Integer screenId;
	private Theaters theaters;
	private String name;
	private int totalSeats;
	private Set<Seats> seatses = new HashSet<Seats>(0);
	private Set<MovieShowtimeScreen> movieShowtimeScreens = new HashSet<MovieShowtimeScreen>(0);

	public Screens() {
	}

	public Screens(Theaters theaters, String name, int totalSeats) {
		this.theaters = theaters;
		this.name = name;
		this.totalSeats = totalSeats;
	}

	public Screens(Theaters theaters, String name, int totalSeats, Set<Seats> seatses,
			Set<MovieShowtimeScreen> movieShowtimeScreens) {
		this.theaters = theaters;
		this.name = name;
		this.totalSeats = totalSeats;
		this.seatses = seatses;
		this.movieShowtimeScreens = movieShowtimeScreens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "screen_id", unique = true, nullable = false)
	public Integer getScreenId() {
		return this.screenId;
	}

	public void setScreenId(Integer screenId) {
		this.screenId = screenId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "theater_id", nullable = false)
	public Theaters getTheaters() {
		return this.theaters;
	}

	public void setTheaters(Theaters theaters) {
		this.theaters = theaters;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "total_seats", nullable = false)
	public int getTotalSeats() {
		return this.totalSeats;
	}

	public void setTotalSeats(int totalSeats) {
		this.totalSeats = totalSeats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "screens")
	public Set<Seats> getSeatses() {
		return this.seatses;
	}

	public void setSeatses(Set<Seats> seatses) {
		this.seatses = seatses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "screens")
	public Set<MovieShowtimeScreen> getMovieShowtimeScreens() {
		return this.movieShowtimeScreens;
	}

	public void setMovieShowtimeScreens(Set<MovieShowtimeScreen> movieShowtimeScreens) {
		this.movieShowtimeScreens = movieShowtimeScreens;
	}

}
