package com.example.demo.entities;
// Generated Dec 2, 2024, 8:44:12 PM by Hibernate Tools 4.3.6.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Seats generated by hbm2java
 */
@Entity
@Table(name = "seats")
public class Seats implements java.io.Serializable {

	private Integer seatId;
	private Screens screens;
	private String seatNumber;
	private BigDecimal price;
	private Showtimes showtimes;
	private Byte status;
	private Set<BookingDetails> bookingDetailses = new HashSet<BookingDetails>(0);
	
	
	public Seats() {
	}

	public Seats(Screens screens, Showtimes showtimes, String seatNumber, BigDecimal price) {
		this.screens = screens;
		this.showtimes = showtimes;
		this.seatNumber = seatNumber;
		this.price = price;
	}

	public Seats(Screens screens, String seatNumber, BigDecimal price, Byte status,
			Set<BookingDetails> bookingDetailses) {
		this.screens = screens;
		this.seatNumber = seatNumber;
		this.price = price;
		this.status = status;
		this.bookingDetailses = bookingDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "seat_id", unique = true, nullable = false)
	public Integer getSeatId() {
		return this.seatId;
	}

	public void setSeatId(Integer seatId) {
		this.seatId = seatId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screen_id", nullable = false)
	public Screens getScreens() {
		return this.screens;
	}

	public void setScreens(Screens screens) {
		this.screens = screens;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "showtime_id", nullable = false)
	public Showtimes getShowtimes() {
		return this.showtimes;
	}

	public void setShowtimes(Showtimes showtimes) {
		this.showtimes = showtimes;
	}
	
	@Column(name = "seat_number", nullable = false, length = 10)
	public String getSeatNumber() {
		return this.seatNumber;
	}

	public void setSeatNumber(String seatNumber) {
		this.seatNumber = seatNumber;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "status")
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seats")
	public Set<BookingDetails> getBookingDetailses() {
		return this.bookingDetailses;
	}

	public void setBookingDetailses(Set<BookingDetails> bookingDetailses) {
		this.bookingDetailses = bookingDetailses;
	}
	
}
	
