package com.example.demo.entities;

// Generated 21:03:18 27 thg 12, 2024 by Hibernate Tools 4.3.6.Final
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Showtimes generated by hbm2java
 */
@Entity
@Table(name = "showtimes")
public class Showtimes implements java.io.Serializable {
	private Integer showtimeId;
	private Date showDate;
	private Date startTime;
	private Date endTime;
	private Boolean isDeleted;
	private Set<BookingDetails> bookingDetailses = new HashSet<BookingDetails>(0);
	private Set<MovieShowtimeScreen> movieShowtimeScreens = new HashSet<MovieShowtimeScreen>(0);

	public Showtimes() {
	}

	public Showtimes(Date showDate, Date startTime, Date endTime, Boolean isDeleted) {
		this.showDate = showDate;
		this.startTime = startTime;
		this.endTime = endTime;
		this.isDeleted = isDeleted;
	}

	public Showtimes(Date showDate, Date startTime, Date endTime, Set<BookingDetails> bookingDetailses,
			Set<MovieShowtimeScreen> movieShowtimeScreens, Boolean isDeleted) {
		this.showDate = showDate;
		this.startTime = startTime;
		this.endTime = endTime;
		this.isDeleted = isDeleted;
		this.bookingDetailses = bookingDetailses;
		this.movieShowtimeScreens = movieShowtimeScreens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "showtime_id", unique = true, nullable = false)
	public Integer getShowtimeId() {
		return this.showtimeId;
	}

	public void setShowtimeId(Integer showtimeId) {
		this.showtimeId = showtimeId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "show_date", nullable = false, length = 10)
	public Date getShowDate() {
		return this.showDate;
	}

	public void setShowDate(Date showDate) {
		this.showDate = showDate;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "start_time", nullable = false, length = 8)
	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "end_time", length = 8)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
	
	@Column(name = "is_deleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "showtimes")
	public Set<BookingDetails> getBookingDetailses() {
		return this.bookingDetailses;
	}

	public void setBookingDetailses(Set<BookingDetails> bookingDetailses) {
		this.bookingDetailses = bookingDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "showtimes")
	public Set<MovieShowtimeScreen> getMovieShowtimeScreens() {
		return this.movieShowtimeScreens;
	}

	public void setMovieShowtimeScreens(Set<MovieShowtimeScreen> movieShowtimeScreens) {
		this.movieShowtimeScreens = movieShowtimeScreens;
	}
}
