package com.example.demo.entities;
// Generated 20:58:42 1 thg 2, 2025 by Hibernate Tools 4.3.6.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Theaters generated by hbm2java
 */
@Entity
@Table(name = "theaters")
public class Theaters implements java.io.Serializable {

	private Integer theaterId;
	private Brands brands;
	private Locations locations;
	private String name;
	private String address;
	private double latitude;
	private double longitude;
	private List<Screens> screenses = new ArrayList<>();
	private List<Movies> movieses = new ArrayList<>();

	public Theaters() {
	}

	public Theaters(Brands brands, Locations locations, String name, double latitude, double longitude) {
		this.brands = brands;
		this.locations = locations;
		this.name = name;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Theaters(Brands brands, Locations locations, String name, String address, double latitude, double longitude,
			List<Screens> screenses, List<Movies> movieses) {
		this.brands = brands;
		this.locations = locations;
		this.name = name;
		this.address = address;
		this.latitude = latitude;
		this.longitude = longitude;
		this.screenses = screenses;
		this.movieses = movieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "theater_id", unique = true, nullable = false)
	public Integer getTheaterId() {
		return this.theaterId;
	}

	public void setTheaterId(Integer theaterId) {
		this.theaterId = theaterId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "brand_id", nullable = false)
	public Brands getBrands() {
		return this.brands;
	}

	public void setBrands(Brands brands) {
		this.brands = brands;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "location_id", nullable = false)
	public Locations getLocations() {
		return this.locations;
	}

	public void setLocations(Locations locations) {
		this.locations = locations;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "latitude", nullable = false, precision = 22, scale = 0)
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 22, scale = 0)
	public double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "theaters")
	public List<Screens> getScreenses() {
		return this.screenses;
	}

	public void setScreenses(List<Screens> screenses) {
		this.screenses = screenses;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "theaterses")
	public List<Movies> getMovieses() {
		return this.movieses;
	}

	public void setMovieses(List<Movies> movieses) {
		this.movieses = movieses;
	}

}
